name: Claude Sync

on:
  schedule:
    - cron: '0 9 * * 1'  # Run every Monday at 9 AM UTC
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '27'
        elixir-version: '1.18'

    - name: Install dependencies
      run: |
        mix local.hex --force
        mix local.rebar --force
        mix deps.get

    - name: Sync Claude
      run: mix claude.install --yes
      
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "Weekly Claude sync"
        title: "Weekly Claude sync"
        body: |
          Weekly automated sync of Claude configuration.
          
          This PR was created automatically by running `mix claude.install --yes`.
        branch: claude-sync-${{ github.run_number }}
        delete-branch: true